// var domainUrl = "http://www.tplm.com/home/"
// var webViewUrl = "http://www.tplm.com/"
var domainUrl = "https://im2.huwing.cn/home/"
var webViewUrl = "https://im2.huwing.cn/"
module.exports = {
  webViewUrl: webViewUrl,
  LookLove: domainUrl + "LookLove/index",
  LookLoveMine: domainUrl + "LookLove/mine",
  LookLoveSharerCat: domainUrl + "LookLove/sharerCat",
  LookLoveCat: domainUrl + "LookLove/loveCat",
  LookLoveSharer: domainUrl + "LookLove/sharer",
  Love_add: domainUrl + "Love/add",
  Love_delImg: domainUrl + "Love/delImg",
  Love_addImg: domainUrl + "Love/addImg",
  Love_backGround : domainUrl + "Love/backGround",
  Love_backGround_cat : domainUrl + "Love/backGround_cat",
  MineSharerCat: domainUrl + "Mine/sharerCat",
  MineAddSharerCat: domainUrl + "Mine/sharerCatAdd",
  MineDelSharerCat: domainUrl + "Mine/sharerCatDel",
  MineSharerImgMove: domainUrl + "Mine/sharerImgMove",
  MineSharerImgDel: domainUrl + "Mine/sharerImgDel",
  MineVideoList: domainUrl + "Mine/sharerVideoList",
  MineVideoChange: domainUrl + "Mine/sharerVideoChange",
  MineAllXp: domainUrl + "Mine/allXp",
  MineSharerImgadd:domainUrl + "Mine/sharerImgadd",
  Collect:domainUrl + "Collect/collect",
  CollectDel:domainUrl + "Collect/collectDel",
  CollectRead:domainUrl + "Collect/collectRead",
  CollectOne:domainUrl + "Collect/collectOne",
  SharerUserList:domainUrl + "Collect/sharerUserList",
  IndexLook:domainUrl + "Index/indexLook",
  IndexSharerCat:domainUrl + "Index/indexSharerCat",
  MineSharerOne:domainUrl + "Mine/sharerOne",
  MineSharerOneRead:domainUrl + "Mine/sharerOneRead",
  MineSharerOneDel:domainUrl + "Mine/sharerOneDel",
  MineSharerHb:domainUrl + "Mine/sharerHB",
  Minece:domainUrl + "Mine/ce",  //测试连接
  MineUserXp:domainUrl + "Mine/userXp",
  MineUserXpDel:domainUrl + "Mine/userDelXp",
  MineUserBC:domainUrl + "Mine/userBC",
  MineUserBX:domainUrl + "Mine/userBX",
  MineUserBCDel:domainUrl + "Mine/userBCDel",
  MineUserAddBC:domainUrl + "Mine/userAddBC",
  MineUserAddLC:domainUrl + "Mine/userAddLC",
  MineUserDelBC:domainUrl + "Mine/userDelBC",
  MineUserDelLC:domainUrl + "Mine/userDelLC",
  MineUserBM:domainUrl + "Mine/userBM",
  MineUserLM:domainUrl + "Mine/userLM",
  MindeUpFile:domainUrl + "Mine/userUpFile",
  MineDelBN:domainUrl + "Mine/userDelBN",
  MineSaveB:domainUrl + "Mine/userSaveB",
  MineMyMusic:domainUrl + "Mine/userMyMusic",
  MineUserMusicDel:domainUrl + "Mine/userMyMusicDel",
  MindeUpVideoFile:domainUrl + "Mine/userUpVideoFile",
  MindeSaveVideo:domainUrl + "Mine/userSaveVideo",
  MineUserVideoDel:domainUrl + "Mine/userVideoDel",
  IndexSharerLsit:domainUrl + "Index/sharerLsit",
  IndexSharerLove:domainUrl + "Index/sharerLove",
  MineUserInfo:domainUrl + "Mine/userInfo",
  IndexgetOpenId:domainUrl + "Index/getOpenId",
  MineUserLC:domainUrl + "Mine/userLC",
}