var domain = "http://www.tplm.com/home/";
var domainUrl = "http://www.tplm.com/home/"
var webUrl = "http://www.tplm.com/home/"
module.exports = {
  LookLove: domainUrl + "LookLove/index",
  LookLoveSharerCat: domainUrl + "LookLove/sharerCat",
  LookLoveSharer: domainUrl + "LookLove/sharer",
  Love_add: domainUrl + "Love/add",
  Love_delImg: domainUrl + "Love/delImg",
  Love_addImg: domainUrl + "Love/addImg",
  Love_backGround : domainUrl + "Love/backGround",
  Love_backGround_cat : domainUrl + "Love/backGround_cat",
  MineSharerCat: domainUrl + "Mine/sharerCat",
  MineAddSharerCat: domainUrl + "Mine/sharerCatAdd",
  MineDelSharerCat: domainUrl + "Mine/sharerCatDel",
  MineSharerImgMove: domainUrl + "Mine/sharerImgMove",
  MineSharerImgDel: domainUrl + "Mine/sharerImgDel",
  MineVideoList: domainUrl + "Mine/sharerVideoList",
  MineVideoChange: domainUrl + "Mine/sharerVideoChange",
  MineAllXp: domainUrl + "Mine/allXp",
  MineSharerImgadd:domainUrl + "Mine/sharerImgadd",
  Collect:domainUrl + "Collect/collect",
  CollectDel:domainUrl + "Collect/collectDel",
  CollectRead:domainUrl + "Collect/collectRead",
  CollectOne:domainUrl + "Collect/collectOne",
  SharerUserList:domainUrl + "Collect/sharerUserList",
  IndexLook:domainUrl + "Index/indexLook",
  IndexSharerCat:domainUrl + "Index/indexSharerCat",
  MineSharerOne:domainUrl + "Mine/sharerOne",
  MineSharerOneRead:domainUrl + "Mine/sharerOneRead",
  MineSharerOneDel:domainUrl + "Mine/sharerOneDel",
  MineSharerHb:domainUrl + "Mine/sharerHB",
  Minece:domainUrl + "Mine/ce",
}